version: '3.9'

services:
  # Banco de Dados MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: vendasdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  # RabbitMQ para mensageria
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

  # Serviço de Vendas
  vendasservice:
    build:
      context: .
      dockerfile: VendasService/Dockerfile
    container_name: vendasservice
    depends_on:
      - mysql
      - rabbitmq
    environment:
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=vendasdb;user=root;password=123456
    ports:
      - "5001:5001"
    networks:
      - backend

  # Serviço de Estoque
  estoqueservice:
    build:
      context: .
      dockerfile: EstoqueService/Dockerfile
    container_name: estoqueservice
    depends_on:
      - mysql
      - rabbitmq
    environment:
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=estoquedb;user=root;password=123456
    ports:
      - "5002:5002"
    networks:
      - backend

  # API Gateway com Ocelot
  apigateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    container_name: apigateway
    depends_on:
      - vendasservice
      - estoqueservice
    ports:
      - "8080:8080"
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
    driver: bridge
